// <auto-generated />
using System;
using DaisyStudy.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaisyStudy.Data.Migrations
{
    [DbContext(typeof(DaisyStudyDbContext))]
    [Migration("20221011130332_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DaisyStudy.Data.Entities.Answer", b =>
                {
                    b.Property<int>("Answer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Answer_ID"), 1L, 1);

                    b.Property<string>("AnswerString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Question_ID")
                        .HasColumnType("int");

                    b.HasKey("Answer_ID");

                    b.HasIndex("Question_ID");

                    b.ToTable("Answers", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppConfigs", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Chat", b =>
                {
                    b.Property<int>("Class_ID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatetimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dislikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Likes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("User_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Class_ID");

                    b.ToTable("Chats", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Class", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassRoom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class_ID")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEOAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEOClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEODescriptione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("Teacher_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tuition")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("isPublic")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Classes", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ClassDetail", b =>
                {
                    b.Property<int>("Class_ID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Student_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Class_ID");

                    b.ToTable("ClassDetails", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Notification_ID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatetimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dislikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Likes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("User_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Notification_ID");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Contact", b =>
                {
                    b.Property<int>("Contact_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Contact_ID"), 1L, 1);

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Contact_ID");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ExamResult", b =>
                {
                    b.Property<int>("ExamResult_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamResult_ID"), 1L, 1);

                    b.Property<float>("Mark")
                        .HasColumnType("real");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentExam_ID")
                        .HasColumnType("int");

                    b.HasKey("ExamResult_ID");

                    b.ToTable("ExamResults", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ExamResultDetail", b =>
                {
                    b.Property<int>("ExamResultDetail_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamResultDetail_ID"), 1L, 1);

                    b.Property<int>("Answer_ID")
                        .HasColumnType("int");

                    b.Property<int>("ExamResult_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.HasKey("ExamResultDetail_ID");

                    b.HasIndex("Answer_ID");

                    b.HasIndex("ExamResult_ID");

                    b.ToTable("ExamResultDetails", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ExamSchedule", b =>
                {
                    b.Property<int>("ExamSchedule_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamSchedule_ID"), 1L, 1);

                    b.Property<int>("Class_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatetimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExamDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamScheduleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamTime")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExamSchedule_ID");

                    b.HasIndex("Class_ID");

                    b.ToTable("ExamSchedules", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Homework", b =>
                {
                    b.Property<int>("Homework_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Homework_ID"), 1L, 1);

                    b.Property<int>("Class_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatetimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeworkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Homework_ID");

                    b.HasIndex("Class_ID");

                    b.ToTable("Homeworks", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Notification_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Notification_ID"), 1L, 1);

                    b.Property<int>("Class_ID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatetimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Notification_ID");

                    b.HasIndex("Class_ID");

                    b.ToTable("Notifycations", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Question", b =>
                {
                    b.Property<int>("Question_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Question_ID"), 1L, 1);

                    b.Property<int>("ExamSchedule_ID")
                        .HasColumnType("int");

                    b.Property<float>("Point")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("QuestionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Question_ID");

                    b.HasIndex("ExamSchedule_ID");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.StudentExam", b =>
                {
                    b.Property<int>("StudentExam_ID")
                        .HasColumnType("int");

                    b.Property<int>("ExamSchedule_ID")
                        .HasColumnType("int");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.HasKey("StudentExam_ID");

                    b.HasIndex("ExamSchedule_ID");

                    b.ToTable("StudentExam");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Submission", b =>
                {
                    b.Property<int>("Homework_ID")
                        .HasColumnType("int");

                    b.Property<float>("Mark")
                        .HasColumnType("real");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Student_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubmissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Homework_ID");

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Transaction", b =>
                {
                    b.Property<int>("Transaction_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Transaction_ID"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExternalTransactionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Transaction_ID");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Answer", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("Question_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Chat", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Class", "Class")
                        .WithMany("Chats")
                        .HasForeignKey("Class_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ClassDetail", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Class", "Class")
                        .WithMany("ClassDetails")
                        .HasForeignKey("Class_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Comment", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Notification", "Notification")
                        .WithMany("Comments")
                        .HasForeignKey("Notification_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ExamResultDetail", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Answer", "Answer")
                        .WithMany("ExamResultDetails")
                        .HasForeignKey("Answer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaisyStudy.Data.Entities.ExamResult", "ExamResult")
                        .WithMany("ExamResultDetails")
                        .HasForeignKey("ExamResult_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("ExamResult");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ExamSchedule", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Class", "Class")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("Class_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Homework", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Class", "Class")
                        .WithMany("Homeworks")
                        .HasForeignKey("Class_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Notification", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Class", "Class")
                        .WithMany("Notifications")
                        .HasForeignKey("Class_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Question", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.ExamSchedule", "ExamSchedule")
                        .WithMany("Questions")
                        .HasForeignKey("ExamSchedule_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSchedule");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.StudentExam", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.ExamSchedule", "ExamSchedule")
                        .WithMany("StudentExams")
                        .HasForeignKey("ExamSchedule_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaisyStudy.Data.Entities.ExamResult", "ExamResult")
                        .WithOne("StudentExam")
                        .HasForeignKey("DaisyStudy.Data.Entities.StudentExam", "StudentExam_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamResult");

                    b.Navigation("ExamSchedule");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Submission", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Homework", "Homework")
                        .WithMany("Submissions")
                        .HasForeignKey("Homework_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Homework");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Answer", b =>
                {
                    b.Navigation("ExamResultDetails");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Class", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("ClassDetails");

                    b.Navigation("ExamSchedules");

                    b.Navigation("Homeworks");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ExamResult", b =>
                {
                    b.Navigation("ExamResultDetails");

                    b.Navigation("StudentExam")
                        .IsRequired();
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ExamSchedule", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("StudentExams");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Homework", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Notification", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
