// <auto-generated />
using System;
using DaisyStudy.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaisyStudy.Data.Migrations
{
    [DbContext(typeof(DaisyStudyDbContext))]
    partial class DaisyStudyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DaisyStudy.Data.Entities.Answer", b =>
                {
                    b.Property<int>("Answer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Answer_ID"), 1L, 1);

                    b.Property<string>("AnswerString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Question_ID")
                        .HasColumnType("int");

                    b.HasKey("Answer_ID");

                    b.HasIndex("Question_ID");

                    b.ToTable("Answers", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppConfigs", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Chat", b =>
                {
                    b.Property<int>("Chat_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Chat_ID"), 1L, 1);

                    b.Property<int>("Class_ID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatetimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dislikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Likes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("User_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Chat_ID");

                    b.HasIndex("Class_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Chats", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Class", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassRoom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class_ID")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEOAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEOClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEODescriptione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tuition")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("isPublic")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Classes", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ClassDetail", b =>
                {
                    b.Property<int>("Class_ID")
                        .HasColumnType("int");

                    b.Property<Guid>("User_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Class_ID", "User_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("ClassDetails", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Comment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Comment_ID"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatetimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dislikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Likes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Notification_ID")
                        .HasColumnType("int");

                    b.Property<Guid>("User_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Comment_ID");

                    b.HasIndex("Notification_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Contact", b =>
                {
                    b.Property<int>("Contact_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Contact_ID"), 1L, 1);

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Contact_ID");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ExamSchedule", b =>
                {
                    b.Property<int>("ExamSchedule_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamSchedule_ID"), 1L, 1);

                    b.Property<int>("Class_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatetimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExamDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamScheduleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamTime")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExamSchedule_ID");

                    b.HasIndex("Class_ID");

                    b.ToTable("ExamSchedules", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Homework", b =>
                {
                    b.Property<int>("Homework_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Homework_ID"), 1L, 1);

                    b.Property<int>("Class_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatetimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeworkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Homework_ID");

                    b.HasIndex("Class_ID");

                    b.ToTable("Homeworks", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Notification_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Notification_ID"), 1L, 1);

                    b.Property<int>("Class_ID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatetimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Notification_ID");

                    b.HasIndex("Class_ID");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Question", b =>
                {
                    b.Property<int>("Question_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Question_ID"), 1L, 1);

                    b.Property<int>("ExamSchedule_ID")
                        .HasColumnType("int");

                    b.Property<float>("Point")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("QuestionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Question_ID");

                    b.HasIndex("ExamSchedule_ID");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.StudentExam", b =>
                {
                    b.Property<int>("StudentExam_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentExam_ID"), 1L, 1);

                    b.Property<int>("ExamSchedule_ID")
                        .HasColumnType("int");

                    b.Property<float>("Mark")
                        .HasColumnType("real");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Student_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentExam_ID");

                    b.HasIndex("ExamSchedule_ID");

                    b.HasIndex("Student_ID");

                    b.ToTable("StudentExams", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.StudentExamDetail", b =>
                {
                    b.Property<int>("StudentExamDetail_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentExamDetail_ID"), 1L, 1);

                    b.Property<int>("Answer_ID")
                        .HasColumnType("int");

                    b.Property<int>("StudentExam_ID")
                        .HasColumnType("int");

                    b.HasKey("StudentExamDetail_ID");

                    b.HasIndex("Answer_ID");

                    b.HasIndex("StudentExam_ID");

                    b.ToTable("StudentExamDetails", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Submission", b =>
                {
                    b.Property<int>("Homework_ID")
                        .HasColumnType("int");

                    b.Property<Guid>("Student_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeSubmission")
                        .HasColumnType("datetime2");

                    b.Property<float>("Mark")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Homework_ID", "Student_ID");

                    b.HasIndex("Student_ID");

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Transaction", b =>
                {
                    b.Property<int>("Transaction_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Transaction_ID"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExternalTransactionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Transaction_ID");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens", (string)null);
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Answer", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("Question_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Chat", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Class", "Class")
                        .WithMany("Chats")
                        .HasForeignKey("Class_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaisyStudy.Data.Entities.AppUser", "AppUser")
                        .WithMany("Chats")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ClassDetail", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Class", "Class")
                        .WithMany("ClassDetails")
                        .HasForeignKey("Class_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaisyStudy.Data.Entities.AppUser", "User")
                        .WithMany("ClassDetails")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Comment", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Notification", "Notification")
                        .WithMany("Comments")
                        .HasForeignKey("Notification_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaisyStudy.Data.Entities.AppUser", "AppUser")
                        .WithMany("Comments")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ExamSchedule", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Class", "Class")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("Class_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Homework", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Class", "Class")
                        .WithMany("Homeworks")
                        .HasForeignKey("Class_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Notification", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Class", "Class")
                        .WithMany("Notifications")
                        .HasForeignKey("Class_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Question", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.ExamSchedule", "ExamSchedule")
                        .WithMany("Questions")
                        .HasForeignKey("ExamSchedule_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSchedule");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.StudentExam", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.ExamSchedule", "ExamSchedule")
                        .WithMany("StudentExams")
                        .HasForeignKey("ExamSchedule_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaisyStudy.Data.Entities.AppUser", "Student")
                        .WithMany("StudentExams")
                        .HasForeignKey("Student_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSchedule");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.StudentExamDetail", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Answer", "Answer")
                        .WithMany("StudentExamDetails")
                        .HasForeignKey("Answer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaisyStudy.Data.Entities.StudentExam", "StudentExam")
                        .WithMany("StudentExamDetails")
                        .HasForeignKey("StudentExam_ID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("StudentExam");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Submission", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.Homework", "Homework")
                        .WithMany("Submissions")
                        .HasForeignKey("Homework_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaisyStudy.Data.Entities.AppUser", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("Student_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Homework");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Transaction", b =>
                {
                    b.HasOne("DaisyStudy.Data.Entities.AppUser", "AppUser")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Answer", b =>
                {
                    b.Navigation("StudentExamDetails");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.AppUser", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("ClassDetails");

                    b.Navigation("Comments");

                    b.Navigation("StudentExams");

                    b.Navigation("Submissions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Class", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("ClassDetails");

                    b.Navigation("ExamSchedules");

                    b.Navigation("Homeworks");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.ExamSchedule", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("StudentExams");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Homework", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Notification", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("DaisyStudy.Data.Entities.StudentExam", b =>
                {
                    b.Navigation("StudentExamDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
